In [63]:
#import libraries
import os
import glob
import scipy
import string
import numpy as np
import tensorflow.python.keras
import os.path as path
from scipy import misc
from keras.utils import np_utils
from PIL import Image
from keras.models import Sequential,Model,save_model
from keras.utils import plot_model
from sklearn.preprocessing import LabelBinarizer
from keras.optimizers import Adam
from keras import applications
from sklearn.preprocessing import OneHotEncoder


import matplotlib.pyplot as plot
from sklearn.model_selection import StratifiedKFold
from keras.layers import Conv2D, MaxPool2D, Flatten, GlobalAvgPool2D, GlobalMaxPool2D, Dense,Dropout

In [57]:
labels = []
images= []
i=0
#input image as arrays and labels
file_paths = glob.glob("C:\MyLearnings\DeepLearning\Currency\\Dataset\\Resizedcurrency\\Augmentdata\\TotalDataset\\Rs50\\*.jpeg")
for image in file_paths:
    im = Image.open(image)
    images.append(np.asarray(im)) #.transpose(1, 0, 2))
    labels.append(1)
    i+=1

print(np.array(images).shape)
limiter=0
file_paths = glob.glob("C:\MyLearnings\\DeepLearning\\Currency\\Dataset\\Resizedcurrency\\Augmentdata\\TotalDataset\\Rs100\\*.jpeg")
for image in file_paths:
    im = Image.open(image)
    images.append(np.asarray(im)) #.transpose(1, 0, 2))
    labels.append(2)
    i+=1

print(np.array(images).shape)

file_paths = glob.glob("C:\MyLearnings\\DeepLearning\\Currency\\Dataset\\Resizedcurrency\\Augmentdata\\TotalDataset\\Rs500\\*.jpeg")
for image in file_paths:
    im = Image.open(image)
    images.append(np.asarray(im)) #.transpose(1, 0, 2))
    labels.append(3)
    i+=1

print(np.array(images).shape)
#one hot encode labels
onehot_encoder = OneHotEncoder(sparse=False)
labels = np.array(labels)
labels = labels.reshape(-1,1)
labels = onehot_encoder.fit_transform(labels)


print(labels.shape)


(180, 224, 224, 3)
(392, 224, 224, 3)
(650, 224, 224, 3)
(650, 3)


In [42]:
#design  model
model = applications.VGG16(weights = "imagenet", include_top=False, input_shape = (224, 224, 3))
for layer in model.layers[:17]:
    layer.trainable = False
x = model.output
x = Flatten()(x)
x = Dense(256, activation="relu")(x)
x = Dropout(0.3)(x)
x = Dense(4096, activation="relu")(x)
predictions = Dense(3, activation="softmax")(x)
model_final = Model(input = model.input, output = predictions)

model_final.compile(loss = "categorical_crossentropy", optimizer = 'adam', metrics=["accuracy"])



model_final.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0   

C:\Users\Ramya\anaconda3\envs\tf-gpu\lib\site-packages\ipykernel_launcher.py:11: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("de...)`
  # This is added back by InteractiveShellApp.init_path()


In [60]:
#compile and fit model
history = model_final.fit(np.array(images), labels, epochs=5, validation_split= 0.2,batch_size=8)


Train on 520 samples, validate on 130 samples
Epoch 1/5
520/520 [==============================] - 41s 78ms/step - loss: 4.4036 - accuracy: 0.5788 - val_loss: 1.6709 - val_accuracy: 0.8154
Epoch 2/5
520/520 [==============================] - 37s 71ms/step - loss: 1.1393 - accuracy: 0.8788 - val_loss: 3.9687 - val_accuracy: 0.7308
Epoch 3/5
520/520 [==============================] - 38s 73ms/step - loss: 1.4121 - accuracy: 0.9135 - val_loss: 0.6922 - val_accuracy: 0.8769
Epoch 4/5
520/520 [==============================] - 38s 73ms/step - loss: 0.2775 - accuracy: 0.9712 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 5/5
520/520 [==============================] - 38s 73ms/step - loss: 0.2566 - accuracy: 0.9865 - val_loss: 0.1468 - val_accuracy: 0.9769


In [ ]:
#test on test sets

In [64]:
#save models
# serialize model to JSON
"""
model_json = model_final.to_json()
with open("C:\MyLearnings\DeepLearning\Currency\\Dataset\\Resizedcurrency\\Model\\model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model_final.save_weights("C:\MyLearnings\\DeepLearning\\Currency\\Dataset\\Resizedcurrency\\Model\\model.h5")
print("Saved model to disk")
"""
model_final.save_model("C:\MyLearnings\DeepLearning\Currency\Dataset\\Resizedcurrency\\Model\\saved_model.h5",save_format='h5')

AttributeError: 'Model' object has no attribute 'save_model'

In [71]:
images_pred= []
labels_pred=[]
i=0
#input image as arrays and labels
file_paths = glob.glob("C:\MyLearnings\DeepLearning\Currency\Dataset\\Resizedcurrency\\Augmentdata\\Aug\\test\\Rs50\\*.jpeg")
for image in file_paths:
    im = Image.open(image)
    images_pred.append(np.asarray(im)) #.transpose(1, 0, 2))
    i+=1
    labels_pred.append(1)
    
file_paths = glob.glob("C:\MyLearnings\DeepLearning\Currency\Dataset\\Resizedcurrency\\Augmentdata\\Aug\\test\\Rs100\\*.jpeg")
for image in file_paths:
    im = Image.open(image)
    images_pred.append(np.asarray(im)) #.transpose(1, 0, 2))
    i+=1
    labels_pred.append(2)
    
file_paths = glob.glob("C:\MyLearnings\DeepLearning\Currency\Dataset\\Resizedcurrency\\Augmentdata\\Aug\\test\\Rs500\\*.jpeg")
for image in file_paths:
    im = Image.open(image)
    images_pred.append(np.asarray(im)) #.transpose(1, 0, 2))
    i+=1
    labels_pred.append(3)    
    
    
images_pred = np.array(images_pred)
onehot_encoder = OneHotEncoder(sparse=False)
labels_pred = np.array(labels_pred)
labels_pred = labels_pred.reshape(-1,1)
labels_pred = onehot_encoder.fit_transform(labels_pred)
print(images_pred.shape)
print(labels_pred.shape)
scores = model_final.evaluate(images_pred,labels_pred,batch_size=8)
print("%s: %.2f%%" % (model_final.metrics_names[1], scores[1]*100))
    

(126, 224, 224, 3)
(126, 3)
126/126 [==============================] - 10s 77ms/step
accuracy: 100.00%


In [74]:
im = Image.open("C:\MyLearnings\DeepLearning\Currency\Dataset\\Resizedcurrency\\Augmentdata\\test\\Rs100\\IMG-20200503-WA0038.jpeg")
image_new = np.array(im)
image_new = np.expand_dims(image_new, axis=0)

print(model_final.predict(image_new))


[[0. 1. 0.]]


In [76]:
im = Image.open("C:\MyLearnings\DeepLearning\Currency\Dataset\\Resizedcurrency\\Augmentdata\\test\\Rs50\\IMG-20200503-WA0058.jpeg")
image_new = np.array(im)
image_new = np.expand_dims(image_new, axis=0)

print(model_final.predict(image_new))


[[1. 0. 0.]]


In [77]:
im = Image.open("C:\MyLearnings\DeepLearning\Currency\Dataset\\Resizedcurrency\\Augmentdata\\test\\Rs500\\IMG-20200503-WA0015.jpeg")
image_new = np.array(im)
image_new = np.expand_dims(image_new, axis=0)

print(model_final.predict(image_new))


[[6.4342842e-09 1.4946654e-06 9.9999845e-01]]
